# Generated by Django 4.2.3 on 2023-07-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('surface_type', models.CharField(max_length=100, verbose_name='Тип поверхности')),
                ('osv', models.CharField(max_length=3, verbose_name='Осв')),
                ('side', models.CharField(max_length=3, verbose_name='Сторона')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('vn_code', models.CharField(max_length=15, verbose_name='Вн.код')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('photo_diagram', models.URLField(verbose_name='Фото/Схема')),
                ('price_with_VAT', models.FloatField(null=True, verbose_name='Прайс c НДС')),
                ('count_impressions', models.IntegerField(null=True, verbose_name='Диджтал кол-во показов')),
                ('GRP', models.FloatField(null=True, verbose_name='GRP')),
                ('OTS', models.FloatField(null=True, verbose_name='OTS')),
                ('code_espar', models.CharField(max_length=20, null=True, verbose_name='КодЭспар')),
                ('july2023', models.TextField(null=True, verbose_name='Июль 2023')),
                ('august2023', models.TextField(null=True, verbose_name='Август 2023')),
                ('september2023', models.TextField(null=True, verbose_name='Сентябрь 2023')),
                ('october2023', models.TextField(null=True, verbose_name='Октябрь 2023')),
                ('november2023', models.TextField(null=True, verbose_name='Ноябрь 2023')),
                ('december2023', models.TextField(null=True, verbose_name='Декабрь 2023')),
                ('material', models.TextField(null=True, verbose_name='Материал носителя')),
                ('product_restriction', models.TextField(null=True, verbose_name='Ограничения по продукту')),
                ('city_district', models.CharField(max_length=50, null=True, verbose_name='Городской округ')),
                ('tech_requirements', models.URLField(null=True, verbose_name='Технические требования')),
                ('mounting_price_with_VAT', models.FloatField(null=True, verbose_name='Монтаж. Прайс  с НДС')),
                ('regluing_price_with_VAT', models.FloatField(null=True, verbose_name='Переклейка. Прайс с НДС')),
                ('resolution_PO', models.DateField(null=True, verbose_name='Разрешение ПО')),
                ('note', models.TextField(verbose_name='Примечание')),
            ],
        ),
    ]
