# Generated by Django 4.2.3 on 2023-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadin_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employ',
            old_name='GRP',
            new_name='grp',
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='mounting_price_with_VAT',
            new_name='mounting_price_with_vat',
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='OTS',
            new_name='ots',
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='price_with_VAT',
            new_name='price_with_vat',
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='regluing_price_with_VAT',
            new_name='regluing_price_with_vat',
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='resolution_PO',
            new_name='resolution_po',
        ),
        migrations.AlterField(
            model_name='employ',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='code_espar',
            field=models.CharField(max_length=30, null=True, verbose_name='КодЭспар'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='count_impressions',
            field=models.FloatField(default=0, null=True, verbose_name='Диджтал кол-во показов'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employ',
            name='side',
            field=models.CharField(max_length=5, verbose_name='Сторона'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='vn_code',
            field=models.CharField(max_length=30, verbose_name='Вн.код'),
        ),
    ]
