# Generated by Django 4.2.3 on 2023-07-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadin_db', '0004_alter_employ_resolution_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='resolution_po',
            field=models.DateTimeField(null=True, verbose_name='Разрешение ПО'),
        ),
    ]
